services:
  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: prompta
      POSTGRES_PASSWORD: prompta
      POSTGRES_DB: prompta_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "prompta"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - prompta
    # Optional: Uncomment to expose the database port to the host
    # ports:
    #   - "5432:5432"

  api:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://prompta:prompta@db:5432/prompta_db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - prompta

networks:
  prompta:

volumes:
  postgres_data:
