"""Remove directory column from projects table

Revision ID: 9f51109fbe46
Revises: a8bc63e5baff
Create Date: 2025-06-03 00:19:52.069884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f51109fbe46'
down_revision: Union[str, None] = 'a8bc63e5baff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_directory'), table_name='projects')
    op.drop_column('projects', 'directory')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('directory', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_projects_directory'), 'projects', ['directory'], unique=False)
    # ### end Alembic commands ###
