"""add is_public attribute to project

Revision ID: a8bc63e5baff
Revises: ce2f514bd1a7
Create Date: 2025-06-02 22:32:12.335803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8bc63e5baff'
down_revision: Union[str, None] = 'ce2f514bd1a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_public', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_public')
    # ### end Alembic commands ###
