// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppcdhjlzaznneiuxzzuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwY2Roamx6YXpubmVpdXh6enV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MzkyNDAsImV4cCI6MjA2NTAxNTI0MH0.XzRYHbtey6I3B-24_ym15tCLoLeZicYUOTqCCHk9oPQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);